export const MOCK_PROFILE = {
  "login": "Cherepahaz",
  "id": 96309370,
  "node_id": "U_kgDOBb2Qeg",
  "avatar_url": "https://avatars.githubusercontent.com/u/96309370?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Cherepahaz",
  "html_url": "https://github.com/Cherepahaz",
  "followers_url": "https://api.github.com/users/Cherepahaz/followers",
  "following_url": "https://api.github.com/users/Cherepahaz/following{/other_user}",
  "gists_url": "https://api.github.com/users/Cherepahaz/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Cherepahaz/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Cherepahaz/subscriptions",
  "organizations_url": "https://api.github.com/users/Cherepahaz/orgs",
  "repos_url": "https://api.github.com/users/Cherepahaz/repos",
  "events_url": "https://api.github.com/users/Cherepahaz/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Cherepahaz/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Дмитрий Замятин",
  "company": null,
  "blog": "",
  "location": "Russian",
  "email": 'qwerty@mail.ru',
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 2,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-12-17T17:18:08Z",
  "updated_at": "2024-06-12T13:56:22Z"
}